# This "input" configures a global authorization rule to enable public access to
# all models in this schema. Learn more about authorization rules here: https://docs.amplify.aws/cli/graphql/authorization-rules
input AMPLIFY { globalAuthRule: AuthRule = { allow: public } } # FOR TESTING ONLY!

type Trail @model
  @auth(rules: [
    { allow: public, operations: [read] },
    { allow: private, operations: [create, update, delete, read] }
  ])
{
  id: ID!
  name: String!
  description: String
  difficulty: String
  distance: Float
  latitude: Float
  longitude: Float
  distanceMiles: Float
  elevationGain: Int
  imageUrl: String
  location: String
  trailPath: String
}
